### ISSUE TITLE
[Bug Report] Art cover and proper username doesn't show up my own playlists in the library section

### ISSUE THREAD

**Issue by IdkWhatToCallMe123** [BobbyESP/Jetispot#21]
### Describe the bug

If I go to the library section a look at my own playlists, it doesn't show the art cover and instead of displaying the name  of the author for the playlist it displays what appear to be a uuid instead.

### Error reports & Screenshots

![Screenshot_20240108-103441](https://github.com/BobbyESP/Jetispot/assets/74187631/50271473-f795-4e62-bede-f4331768d755)

### Device info

Device: Google Pixel 7
OS: Android 14 (stock)
Jetispot ver: 0.1.6

**Comment by Outlet7493** [comment]
I have fixed the username issue.

In regards to pictures, for some reason the Spotify API isn't returning images on the rootlist endpoint, or the playlist endpoint.

I am still investigating this but for now have implemented a patch to save and use the playlist image if it is seen on the home screen. Changes are at https://github.com/Outlet7493/Jetispot and will make a PR when things are ready or I've found a better way of doing it.

**Comment by BobbyESP** [comment]
Nice, okay, thanks mate!

**Comment by BobbyESP** [comment]
> In regards to pictures, for some reason the Spotify API isn't returning images on the rootlist endpoint, or the playlist endpoint. 

I saw these before. If you take a look at the network requests, Spotify tries to retrieve 4 images of the playlists that have no uploaded image. These 4 images are the first 4 songs of the playlist, but they are not requested to the CDN, they have something like the next format: [spotify:artwork:heregoesanid] (the keyword of the middle isn't "artwork", but I don't remember now which one it is. It's been a long time since I took a look at this)
